# Correlated multivariate normal

In [1]:
import numpy as np

In [2]:
sig_v = np.array([2, 5, 2])
cor_m = np.array([[1, 0.7, -0.2], [0.7, 1, 0.5], [-0.2, 0.5, 1]])
print(sig_v, '\n', cor_m)

[2 5 2] 
 [[ 1.   0.7 -0.2]
 [ 0.7  1.   0.5]
 [-0.2  0.5  1. ]]


In [3]:
# Vector * Vector(Matrix * Matrix): Component-wise
print(sig_v * sig_v, '\n')
print(cor_m * cor_m, '\n')

# Matrix x Vector ??: component-wise in each vector
print( cor_m * sig_v, '\n')
print( sig_v * cor_m, '\n') # Same

[ 4 25  4] 

[[ 1.    0.49  0.04]
 [ 0.49  1.    0.25]
 [ 0.04  0.25  1.  ]] 

[[ 2.   3.5 -0.4]
 [ 1.4  5.   1. ]
 [-0.4  2.5  2. ]] 

[[ 2.   3.5 -0.4]
 [ 1.4  5.   1. ]
 [-0.4  2.5  2. ]] 



In [4]:
# Dot(inner) product
print( np.dot(sig_v, sig_v) )
print( sig_v.dot(sig_v) ) # same

33
33


In [5]:
# Matrix multiplication ?
print(cor_m @ cor_m, '\n')

print(np.matmul(cor_m, sig_v), '\n')  # sig_v is treated as a column vector

print(np.matmul(sig_v, cor_m)) # sig_v is treated as a row vector

[[ 1.53  1.3  -0.05]
 [ 1.3   1.74  0.86]
 [-0.05  0.86  1.29]] 

[ 5.1  7.4  4.1] 

[ 5.1  7.4  4.1]


In [7]:
# Exciplicitly make a column vector
print( np.reshape(sig_v,(3,1)) )
#print( sig_v.reshape((3,1)) )
#sig_v.transpose() # same

[[2]
 [5]
 [2]]


In [6]:
cov_m = sig_v * cor_m * np.reshape(sig_v,(3,1))
print(cov_m)

[[  4.    7.   -0.8]
 [  7.   25.    5. ]
 [ -0.8   5.    4. ]]


In [7]:
# Cholesky decomposition of covariance matrix

chol_m = np.linalg.cholesky(cov_m)
print(chol_m)

[[ 2.          0.          0.        ]
 [ 3.5         3.57071421  0.        ]
 [-0.4         1.79235851  0.79211803]]


In [9]:
# Let's verify that L x L^T = Covariance

print( chol_m @ chol_m.transpose(), '\n' )
print( chol_m @ chol_m.transpose() - cov_m )

[[  4.    7.   -0.8]
 [  7.   25.    5. ]
 [ -0.8   5.    4. ]] 

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [10]:
# Now let's create multivariate normal random variables following the covariance matrix

# First, create standard normals (1000x3)

znorm_m = np.random.normal(size=(3, 10000))
znorm_m

array([[-1.00961347,  1.36113387, -1.03805982, ..., -0.24931149,
        -1.23352916, -1.97188792],
       [-1.63228497,  2.51558454,  0.61215359, ..., -0.8627275 ,
        -0.09129585,  0.31072263],
       [-0.10433959, -1.75305044, -0.28620661, ..., -0.2094462 ,
        -1.02393013,  0.26219418]])

In [11]:
# Then multiply C^T

#xnorm_m = znorm_m @ chol_m.transpose()
xnorm_m = chol_m @ znorm_m
xnorm_m

array([[ -2.01922695,   2.72226775,  -2.07611964, ...,  -0.49862298,
         -2.46705832,  -3.94377584],
       [ -9.36207029,  13.74640201,  -1.44738385, ...,  -3.95314355,
         -4.64334345,  -5.79210601],
       [ -2.60444373,   2.57575292,   1.2857132 , ...,  -1.61249848,
         -0.48129675,   1.55337025]])

In [12]:
# Let's verify that X = C * Z  follows the covariance
print(cov_m)
cov_m_sample = np.cov( xnorm_m )
print( 'Cov from sample:\n', cov_m_sample )
print( 'Error:\n', cov_m_sample - cov_m )

[[  4.    7.   -0.8]
 [  7.   25.    5. ]
 [ -0.8   5.    4. ]]
Cov from sample:
 [[  4.07059587   7.11571297  -0.79378447]
 [  7.11571297  25.26594799   4.98654495]
 [ -0.79378447   4.98654495   3.94743611]]
Error:
 [[ 0.07059587  0.11571297  0.00621553]
 [ 0.11571297  0.26594799 -0.01345505]
 [ 0.00621553 -0.01345505 -0.05256389]]


In [15]:
# also check the correation
print(cor_m)
cor_m_sample = np.corrcoef( xnorm_m )
print( 'Corr from sample:\n', cor_m_sample )
print( 'Error:\n', cor_m_sample - cor_m )

[[ 1.   0.7 -0.2]
 [ 0.7  1.   0.5]
 [-0.2  0.5  1. ]]
Corr from sample:
 [[ 1.          0.70165178 -0.19802319]
 [ 0.70165178  1.          0.49931474]
 [-0.19802319  0.49931474  1.        ]]
Error:
 [[ -2.22044605e-16   1.65177592e-03   1.97681109e-03]
 [  1.65177592e-03   0.00000000e+00  -6.85262936e-04]
 [  1.97681109e-03  -6.85262936e-04  -1.11022302e-16]]
