# Tensor Manipulation
__[Notice]__ This contents is slightly modified from the python notebook at https://github.com/hunkim/DeepLearningZeroToAll

In [115]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

## Simple Array

In [116]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


# 2D Array

In [117]:
# Numpy Array
# row first, column next
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


## Shape, Rank, Axis

In [118]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [119]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [120]:
array4d = [
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]
array4d

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [121]:
t = tf.constant(array4d)
tf.shape(t).eval()

array([1, 2, 3, 4])

## Matmul VS multiply

In [122]:
matrix1 = tf.constant([[3., 3.]]) # a matrix with a single row
matrix2 = tf.constant([[2.],[2.]]) # a matrix with a single column
#matrix2 = tf.transpose( tf.constant([[2.,2.]]) ) # a matrix with a single column
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [123]:
# Tensor operation goes element by element
print( (matrix1*matrix2).eval(), "\n" )
print( (matrix1*tf.transpose(matrix2)).eval(), "\n" )
print( (matrix2*tf.transpose(matrix1)).eval() )

[[ 6.  6.]
 [ 6.  6.]] 

[[ 6.  6.]] 

[[ 6.]
 [ 6.]]


## Watch out broadcasting

In [124]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [125]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

## Random values for variable initializations 

In [126]:
tf.random_normal([3]).eval() 
#tf.random_normal([1,3]).eval()  #same

array([-1.65287316,  0.9101218 ,  0.8500815 ], dtype=float32)

In [127]:
tf.random_uniform([2]).eval()

array([ 0.16988862,  0.64594197], dtype=float32)

In [128]:
tf.random_uniform([2, 3]).eval()

array([[ 0.81386006,  0.94818664,  0.51996887],
       [ 0.79564977,  0.21361637,  0.98275101]], dtype=float32)

## Reduce Mean/Sum

In [129]:
tf.reduce_mean([1, 2]).eval()

1

In [130]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_sum(x).eval()

10.0

In [131]:
tf.reduce_sum(x, axis=0).eval() # sum over 0-th axis (collapse the 0-th axis)

array([ 4.,  6.], dtype=float32)

In [132]:
tf.reduce_sum(x, axis=1).eval() # sum over 1-th axis (collapse the 0-th axis)

array([ 3.,  7.], dtype=float32)

In [133]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [134]:
tf.reduce_mean(x).eval()

2.5

In [135]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [136]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [137]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [138]:
array3d = [
    [ # <- 0-th axis
        [0,1,2], # <- 1st axis
        [10,11,12],
        [20,21,22]
    ],
    [
        [100,101,102],
        [110,111,112],
        [120,121,122]
    ],
    [
        [200,201,202],
        [210,211,212],
        [220,221,222]
    ]
]
print(np.array(array3d), "\n------------------------\n")
print(array3d[1][1][1])
print(array3d[1][0][2])
print("-----------------------\n")

print(tf.reduce_sum(array3d).eval(), "\n")
print(tf.reduce_sum(array3d, axis=0).eval(), "\n")
print(tf.reduce_sum(array3d, axis=1).eval(), "\n")
print(tf.reduce_sum(array3d, axis=2).eval(), "\n")

print(tf.reduce_sum(array3d, axis=-1).eval(), "\n") # last dimension 

print(tf.reduce_sum(array3d, axis=[1,2]).eval(), "\n")
print(tf.reduce_sum(array3d, axis=[0,1]).eval(), "\n")

[[[  0   1   2]
  [ 10  11  12]
  [ 20  21  22]]

 [[100 101 102]
  [110 111 112]
  [120 121 122]]

 [[200 201 202]
  [210 211 212]
  [220 221 222]]] 
------------------------

111
102
-----------------------

2997 

[[300 303 306]
 [330 333 336]
 [360 363 366]] 

[[ 30  33  36]
 [330 333 336]
 [630 633 636]] 

[[  3  33  63]
 [303 333 363]
 [603 633 663]] 

[[  3  33  63]
 [303 333 363]
 [603 633 663]] 

[  99  999 1899] 

[ 990  999 1008] 



## Argmax with axis

In [143]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [144]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [145]:
#tf.argmax(x, axis=-1).eval()

## Reshape, squeeze, expand_dims

In [146]:
# Numpy ND array
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [147]:
tf.reshape(t, shape=[-1, 3]).eval() # -1: whatever appropriate

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [148]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [149]:
# remove dimensions with size 1.

print(tf.squeeze([[0], [1], [2]]).eval())

print(tf.squeeze(tf.reshape(t, shape=[-1, 1, 3])).eval())

[0 1 2]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [150]:
# Insert extra dimension

print( tf.expand_dims([0, 1, 2], 0).eval(), "\n" )

print( tf.expand_dims([0, 1, 2], 1).eval(), "\n" )

print( tf.expand_dims([[0, 1, 2],[4,5,6]], 1).eval() )


[[0 1 2]] 

[[0]
 [1]
 [2]] 

[[[0 1 2]]

 [[4 5 6]]]


## One hot

In [151]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [152]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

## casting

In [153]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [154]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

## Stack

In [155]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [156]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like and Zeros like

In [157]:
# tensor of value 1 with the same size and type
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [158]:
# tensor of value 0 with the same size and type
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip


In [159]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [160]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [161]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [162]:
# transpose in multi-dimension

t1 = tf.transpose(t, [1, 0, 2])
print(sess.run(t1).shape)
print(sess.run(t1))

(2, 2, 3)
[[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]]


In [163]:
t = tf.transpose(t1, [1, 0, 2])
print(sess.run(t).shape)
print(sess.run(t))

(2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [164]:
t2 = tf.transpose(t, [1, 2, 0])
print(sess.run(t2).shape)
print(sess.run(t2))

(2, 3, 2)
[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


In [165]:
t = tf.transpose(t2, [2, 0, 1])
print(sess.run(t).shape)
print(sess.run(t))

(2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
